language: cpp
os: osx
osx_image: xcode7.3
compiler: clang
sudo: false

before_install:
    - brew update
    - brew install boost sdl2

script:
    - (cd mruby && make -j2)
    - mkdir build
    - cd build
    - cmake -G Xcode ..
    - xcodebuild
    - Debug/app
    - Debug/catch_test
