language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev
            - g++-5
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev
            - clang-3.6
      env: COMPILER=clang++-3.6

    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew install sdl2 sdl2_image sdl2_ttf

script: ./build.sh
